version: 2.1
executors:
  base:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/spatialcurrent/go-try-get
jobs:
  pre_deps_golang:
    executor: base
    steps:
      - checkout
      - run: go get -d ./...
      - run: sudo chown -R circleci /go/src
      - save_cache:
          key: v1-go-src-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src
  test:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install gometalinter
          command: |
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
      - run:
          name: Test
          command: bash scripts/test.sh
workflows:
  main:
    jobs:
      - pre_deps_golang
      - test:
          requires:
            - pre_deps_golang

